const exact_countries: Record<string, string> = {
  'Africa/Cairo': 'Egypt',
  'Africa/Johannesburg': 'South Africa',
  'Africa/Lagos': 'Nigeria',
  'Africa/Nairobi': 'Kenya',
  'America/Anchorage': 'United States',
  'America/Argentina/Buenos_Aires': 'Argentina',
  'America/Bogota': 'Colombia',
  'America/Caracas': 'Venezuela',
  'America/Chicago': 'United States',
  'America/Denver': 'United States',
  'America/Detroit': 'United States',
  'America/Edmonton': 'Canada',
  'America/Guayaquil': 'Ecuador',
  'America/Halifax': 'Canada',
  'America/Havana': 'Cuba',
  'America/Los_Angeles': 'United States',
  'America/Mexico_City': 'Mexico',
  'America/Montevideo': 'Uruguay',
  'America/New_York': 'United States',
  'America/Panama': 'Panama',
  'America/Phoenix': 'United States',
  'America/Puerto_Rico': 'Puerto Rico',
  'America/Santiago': 'Chile',
  'America/Sao_Paulo': 'Brazil',
  'America/Toronto': 'Canada',
  'America/Vancouver': 'Canada',
  'Asia/Almaty': 'Kazakhstan',
  'Asia/Baghdad': 'Iraq',
  'Asia/Bangkok': 'Thailand',
  'Asia/Beirut': 'Lebanon',
  'Asia/Colombo': 'Sri Lanka',
  'Asia/Dhaka': 'Bangladesh',
  'Asia/Dubai': 'United Arab Emirates',
  'Asia/Ho_Chi_Minh': 'Vietnam',
  'Asia/Hong_Kong': 'Hong Kong',
  'Asia/Jakarta': 'Indonesia',
  'Asia/Jerusalem': 'Israel',
  'Asia/Karachi': 'Pakistan',
  'Asia/Kathmandu': 'Nepal',
  'Asia/Kolkata': 'India',
  'Asia/Kuala_Lumpur': 'Malaysia',
  'Asia/Manila': 'Philippines',
  'Asia/Seoul': 'South Korea',
  'Asia/Shanghai': 'China',
  'Asia/Singapore': 'Singapore',
  'Asia/Taipei': 'Taiwan',
  'Asia/Tehran': 'Iran',
  'Asia/Tokyo': 'Japan',
  'Atlantic/Reykjavik': 'Iceland',
  'Europe/Amsterdam': 'Netherlands',
  'Europe/Athens': 'Greece',
  'Europe/Belgrade': 'Serbia',
  'Europe/Berlin': 'Germany',
  'Europe/Brussels': 'Belgium',
  'Europe/Bucharest': 'Romania',
  'Europe/Budapest': 'Hungary',
  'Europe/Copenhagen': 'Denmark',
  'Europe/Dublin': 'Ireland',
  'Europe/Helsinki': 'Finland',
  'Europe/Istanbul': 'Turkey',
  'Europe/Kyiv': 'Ukraine',
  'Europe/Lisbon': 'Portugal',
  'Europe/London': 'United Kingdom',
  'Europe/Madrid': 'Spain',
  'Europe/Oslo': 'Norway',
  'Europe/Paris': 'France',
  'Europe/Prague': 'Czech Republic',
  'Europe/Rome': 'Italy',
  'Europe/Stockholm': 'Sweden',
  'Europe/Vienna': 'Austria',
  'Europe/Warsaw': 'Poland',
  'Europe/Zurich': 'Switzerland',
  'Pacific/Auckland': 'New Zealand',
  'Pacific/Fiji': 'Fiji',
  'Pacific/Guam': 'Guam',
  'Pacific/Honolulu': 'United States',
  'Pacific/Port_Moresby': 'Papua New Guinea',
  'US/Alaska': 'United States',
  'US/Arizona': 'United States',
  'US/Central': 'United States',
  'US/Eastern': 'United States',
  'US/Hawaii': 'United States',
  'US/Mountain': 'United States',
  'US/Pacific': 'United States'
};

const country_prefixes: [string, string][] = [
  ['Antarctica/Macquarie', 'Australia'],
  ['Australia/', 'Australia'],
  ['Brazil/', 'Brazil'],
  ['Canada/', 'Canada'],
  ['Chile/', 'Chile'],
  ['Mexico/', 'Mexico'],
  ['Pacific/Chatham', 'New Zealand']
];

export function estimateCountryFromTimezone(): string | null {
  try {
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (exact_countries[timezone]) return exact_countries[timezone];
    return country_prefixes.find(([prefix]) => timezone.startsWith(prefix))?.[1] ?? null;
  } catch {
    return null;
  }
}
